included:
  - Sources
  - Tests
excluded:
  - Tests/RelayerFrameworkTests/XCTestManifests.swift
  - Package.swift
  - Tests/LinuxMain.swift
identifier_name:
  excluded:
    - id
    - to
    - i
disabled_rules:
    - trailing_comma
