#if !canImport(ObjectiveC)
import XCTest

extension RelayerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RelayerTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RelayerTests.__allTests__RelayerTests),
    ]
}
#endif
